[pytest]
testpaths = tests
cache_dir = app/.pytest_cache
norecursedirs =
    .git
    .pytest_cache
    app/venv
    app/venv.broken
    app/build
    artifacts
    build_tmp
    release
    temp
    pytest-cache-files-*
