param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot ".."))
)

$ErrorActionPreference = "Stop"
$failures = New-Object System.Collections.Generic.List[string]

function Read-RequiredFile([string]$RelativePath) {
    $path = Join-Path $RepoRoot $RelativePath
    if (-not (Test-Path -LiteralPath $path)) {
        $script:failures.Add("Missing file: $RelativePath")
        return ""
    }

    return Get-Content -LiteralPath $path -Raw
}

$redactor = Read-RequiredFile "wpf\Services\SensitiveTextRedactor.cs"
foreach ($token in @(
    "class SensitiveTextRedactor",
    "Environment.UserName",
    "Environment.MachineName",
    "SpecialFolder.UserProfile",
    "JsonSensitiveStringRegex",
    "EmailRegex",
    "KnownSecretRegex"
)) {
    if ($redactor -notmatch [regex]::Escape($token)) {
        $failures.Add("SensitiveTextRedactor missing required marker: $token")
    }
}

foreach ($relativePath in @(
    "wpf\Views\PlacementActionPageBase.cs",
    "wpf\Views\PlacementPageChrome.xaml.cs",
    "wpf\Views\CyberPageChrome.xaml.cs"
)) {
    $text = Read-RequiredFile $relativePath
    if ($text -eq "") {
        continue
    }

    foreach ($token in @("SensitiveTextRedactor.Redact", "Raw JSON (redacted)")) {
        if ($text -notmatch [regex]::Escape($token)) {
            $failures.Add("$relativePath missing redaction marker: $token")
        }
    }

    if ($text -match "Raw JSON\\n") {
        $failures.Add("$relativePath still contains an unredacted raw JSON label.")
    }
}

foreach ($relativePath in @(
    "wpf\MainWindow.xaml.cs",
    "wpf\ViewModels\OneClickBoostViewModel.cs",
    "wpf\ViewModels\PlacementPageViewModel.cs"
)) {
    $text = Read-RequiredFile $relativePath
    if ($text -match "generated by AI|AI-generated") {
        $failures.Add("$relativePath contains AI/template wording that should not appear in Stable UI.")
    }
}

if ($failures.Count -gt 0) {
    Write-Host "FAIL: UI sensitive redaction verification" -ForegroundColor Red
    $failures | ForEach-Object { Write-Host "- $_" }
    exit 1
}

Write-Host "PASS: UI sensitive redaction verification" -ForegroundColor Green
